name: 🐛 Bug Report
description: File a bug report to help us improve the extension
title: "[Bug]: "
labels: ["bug"]
assignees:
  - JOHLC
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! Please provide as much detail as possible to help us resolve it quickly.
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Make sure you're using the latest version of the extension
  
  - type: input
    id: version
    attributes:
      label: Extension Version
      description: What version of the extension are you using? (Check chrome://extensions or edge://extensions)
      placeholder: e.g., 2025.09.2
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Edge
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of your browser are you using?
      placeholder: e.g., Chrome 120.0.6099.199
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you using?
      placeholder: e.g., 2024.1.0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, console logs, etc.)
      placeholder: Any additional information that might help...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using the latest version of the extension
          required: true
        - label: I have provided all the requested information above
          required: true