name: ❓ Question or Help
description: Ask a question about using the extension or getting help with setup
title: "[Question]: "
labels: ["question"]
assignees:
  - JOHLC
body:
  - type: markdown
    attributes:
      value: |
        Need help with the extension? Please provide as much detail as possible so we can assist you.
        
        Before submitting, please:
        - Check the README documentation
        - Search existing issues for similar questions
        - Try the troubleshooting steps in the documentation
  
  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of help do you need?
      options:
        - Installation/Setup
        - Configuration
        - Home Assistant Integration
        - Troubleshooting
        - Usage/How-to
        - Other
    validations:
      required: true

  - type: textarea
    id: question-description
    attributes:
      label: Question or Problem
      description: What would you like help with? Be as specific as possible.
      placeholder: I'm trying to... / I can't figure out how to... / I'm having trouble with...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      placeholder: e.g., 2025.09.2
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Edge
        - Other
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: I've tried... / I followed the instructions but... / I checked...
    validations:
      required: false

  - type: textarea
    id: current-setup
    attributes:
      label: Current Setup
      description: Describe your current Home Assistant setup and how you're trying to use the extension
      placeholder: I have Home Assistant running on... / I'm trying to create an automation that...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or error messages that might help
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have read the README documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true